index:
    path: /
    controller: App\Controller\IndexController::index

liste_new:
    path: /liste/new
    controller: App\Controller\ListeController:createAction

liste_all:
    path: /liste/all
    controller: App\Controller\ListeController::showAction

my_lists:
    path: /my/lists
    controller: App\Controller\ListeController::showOwnLists

liste-delete:
    path: /liste/delete
    controller: App\Controller\ListeController:deleteAction

liste-edit:
    path: /liste/edit
    controller: App\Controller\ListeController:updateAction

task_new:
    path: /task/new
    controller: App\Controller\TaskController:createAction

task_all:
    path: /task/all
    controller: App\Controller\TaskController::showAction

my_tasks:
    path: /my/tasks
    controller: App\Controller\TaskController::showOwnLists

task-delete: 
    path: /task/delete
    controller: App\Controller\TaskController::deleteAction

task-edit:
    path: /task/edit
    controller: App\Controller\TaskController::updateAction